// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaFo0MoOvkEKOk_4x1TOZlnB2H78m8qBU',
    appId: '1:490392334899:web:44469f1eea5ffc620ee946',
    messagingSenderId: '490392334899',
    projectId: 'votacion-delegado-uc',
    authDomain: 'votacion-delegado-uc.firebaseapp.com',
    storageBucket: 'votacion-delegado-uc.firebasestorage.app',
    measurementId: 'G-VFTKQ9NXRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD31OZNrKxSwwQXEN72Gmg68wCZIu2KyII',
    appId: '1:490392334899:android:4125b72ab6732f2e0ee946',
    messagingSenderId: '490392334899',
    projectId: 'votacion-delegado-uc',
    storageBucket: 'votacion-delegado-uc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZqdWFqrHd3fvJxHei7pBzpyKcRQRkCHs',
    appId: '1:490392334899:ios:ee3183a87e5774440ee946',
    messagingSenderId: '490392334899',
    projectId: 'votacion-delegado-uc',
    storageBucket: 'votacion-delegado-uc.firebasestorage.app',
    iosBundleId: 'com.example.votacionDelegadoEc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZqdWFqrHd3fvJxHei7pBzpyKcRQRkCHs',
    appId: '1:490392334899:ios:ee3183a87e5774440ee946',
    messagingSenderId: '490392334899',
    projectId: 'votacion-delegado-uc',
    storageBucket: 'votacion-delegado-uc.firebasestorage.app',
    iosBundleId: 'com.example.votacionDelegadoEc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaFo0MoOvkEKOk_4x1TOZlnB2H78m8qBU',
    appId: '1:490392334899:web:cbde6302025f714c0ee946',
    messagingSenderId: '490392334899',
    projectId: 'votacion-delegado-uc',
    authDomain: 'votacion-delegado-uc.firebaseapp.com',
    storageBucket: 'votacion-delegado-uc.firebasestorage.app',
    measurementId: 'G-JJS4XW22ZH',
  );
}
